# Generated by Django 5.0.8 on 2024-08-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_financial_aid_recipient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_scholarship_recipient',
            field=models.BooleanField(default=False),
        ),
    ]
