# Generated by Django 5.0.8 on 2024-08-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_is_financial_aid_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='yes_or_no',
            field=models.BooleanField(default=False),
        ),
    ]
