# Generated by Django 5.0.8 on 2024-08-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_yes_or_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='yes_or_no',
        ),
    ]
