# Generated by Django 5.0.8 on 2024-08-13 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_yes_or_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
