# Generated by Django 5.0.8 on 2024-08-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='index_number',
            field=models.CharField(default='0000', max_length=50),
        ),
    ]
