# Generated by Django 5.0.8 on 2025-12-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_last_name_alter_student_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_academic_level',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
