services:
  - type: web
    name: Scholarships App
    env: docker
    plan: free # Specify the free plan
    dockerfilePath: ./Dockerfile # Path to your Dockerfile
    buildCommand: "docker-compose -f docker-compose.remote.yml up --build"
    startCommand: "docker-compose -f docker-compose.remote.yml up"
