# Generated by Django 5.0.8 on 2024-08-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examrecords', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examrecord',
            name='date_reference',
        ),
    ]
