# Generated by Django 5.0.8 on 2024-08-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examrecords', '0002_remove_examrecord_date_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examrecord',
            name='grade_awarded',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='special_remarks',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
