# Generated by Django 5.0.8 on 2024-08-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examrecords', '0003_alter_examrecord_grade_awarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrecord',
            name='temp_fff',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
