# Generated by Django 5.0.8 on 2024-08-21 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examrecords', '0004_examrecord_temp_fff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examrecord',
            name='temp_fff',
        ),
    ]
