# Generated by Django 5.0.8 on 2024-08-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['date']},
        ),
    ]
