# Generated by Django 5.0.8 on 2024-08-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patron',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='patron',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='patron',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
