# Generated by Django 5.0.8 on 2024-08-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrons', '0002_rename_name_patron_first_name_patron_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
